//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EBFPEntities : DbContext
    {
        public EBFPEntities()
            : base("name=EBFPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAfterFireOperationBreathingApparatusUsed> tblAfterFireOperationBreathingApparatusUsed { get; set; }
        public virtual DbSet<tblAfterFireOperationDispatchedVehicles> tblAfterFireOperationDispatchedVehicles { get; set; }
        public virtual DbSet<tblAfterFireOperationExtinguishingAgentsUsed> tblAfterFireOperationExtinguishingAgentsUsed { get; set; }
        public virtual DbSet<tblAfterFireOperationHoseLineUsed> tblAfterFireOperationHoseLineUsed { get; set; }
        public virtual DbSet<tblAfterFireOperationOtherToolsUsed> tblAfterFireOperationOtherToolsUsed { get; set; }
        public virtual DbSet<tblAfterFireOperationRopesLadderUsed> tblAfterFireOperationRopesLadderUsed { get; set; }
        public virtual DbSet<tblAfterInspectionReports> tblAfterInspectionReports { get; set; }
        public virtual DbSet<tblAlarmTypes> tblAlarmTypes { get; set; }
        public virtual DbSet<tblArticles> tblArticles { get; set; }
        public virtual DbSet<tblAssetInventories> tblAssetInventories { get; set; }
        public virtual DbSet<tblCourses> tblCourses { get; set; }
        public virtual DbSet<tblDirectorates> tblDirectorates { get; set; }
        public virtual DbSet<tblDutyStatus> tblDutyStatus { get; set; }
        public virtual DbSet<tblEmployeeChildren> tblEmployeeChildren { get; set; }
        public virtual DbSet<tblEmployeeCivilServiceEligibilities> tblEmployeeCivilServiceEligibilities { get; set; }
        public virtual DbSet<tblEmployeeDutyStatusUpdates> tblEmployeeDutyStatusUpdates { get; set; }
        public virtual DbSet<tblEmployeeEducationalBackground> tblEmployeeEducationalBackground { get; set; }
        public virtual DbSet<tblEmployeeLeaveRecords> tblEmployeeLeaveRecords { get; set; }
        public virtual DbSet<tblEmployeeMembershipInAssociationOrganizations> tblEmployeeMembershipInAssociationOrganizations { get; set; }
        public virtual DbSet<tblEmployeeNonAcademicDistinctions> tblEmployeeNonAcademicDistinctions { get; set; }
        public virtual DbSet<tblEmployeeOtherInformation> tblEmployeeOtherInformation { get; set; }
        public virtual DbSet<tblEmployeeReferences> tblEmployeeReferences { get; set; }
        public virtual DbSet<tblEmployeeSpecialSkillsHobbies> tblEmployeeSpecialSkillsHobbies { get; set; }
        public virtual DbSet<tblEstablishmentStatus> tblEstablishmentStatus { get; set; }
        public virtual DbSet<tblFireRecords> tblFireRecords { get; set; }
        public virtual DbSet<tblFireSuppression> tblFireSuppression { get; set; }
        public virtual DbSet<tblIncidentStatus> tblIncidentStatus { get; set; }
        public virtual DbSet<tblIndexTypes> tblIndexTypes { get; set; }
        public virtual DbSet<tblInspectionOrderActions> tblInspectionOrderActions { get; set; }
        public virtual DbSet<tblInspectionOrderInspectors> tblInspectionOrderInspectors { get; set; }
        public virtual DbSet<tblInspectionOrderRemarks> tblInspectionOrderRemarks { get; set; }
        public virtual DbSet<tblInventoryGroups> tblInventoryGroups { get; set; }
        public virtual DbSet<tblJobFunctions> tblJobFunctions { get; set; }
        public virtual DbSet<tblLogisticAssets> tblLogisticAssets { get; set; }
        public virtual DbSet<tblMandatoryTrainings> tblMandatoryTrainings { get; set; }
        public virtual DbSet<tblMedical> tblMedical { get; set; }
        public virtual DbSet<tblNoticeToComply> tblNoticeToComply { get; set; }
        public virtual DbSet<tblNoticeToCorrectViolations> tblNoticeToCorrectViolations { get; set; }
        public virtual DbSet<tblOPSSeries> tblOPSSeries { get; set; }
        public virtual DbSet<tblORSeries> tblORSeries { get; set; }
        public virtual DbSet<tblOtherVehicleModel> tblOtherVehicleModel { get; set; }
        public virtual DbSet<tblOtherVehicles> tblOtherVehicles { get; set; }
        public virtual DbSet<tblPhysicalExam> tblPhysicalExam { get; set; }
        public virtual DbSet<tblPhysicalInventory> tblPhysicalInventory { get; set; }
        public virtual DbSet<tblPopulations> tblPopulations { get; set; }
        public virtual DbSet<tblProvinces> tblProvinces { get; set; }
        public virtual DbSet<tblResidential> tblResidential { get; set; }
        public virtual DbSet<tblRoleAccess> tblRoleAccess { get; set; }
        public virtual DbSet<tblSalaryGrades> tblSalaryGrades { get; set; }
        public virtual DbSet<tblSpoiledOR> tblSpoiledOR { get; set; }
        public virtual DbSet<tblTruckModel> tblTruckModel { get; set; }
        public virtual DbSet<tblTrucks> tblTrucks { get; set; }
        public virtual DbSet<tblUnitDeposits> tblUnitDeposits { get; set; }
        public virtual DbSet<tblUnserviceablePhysicalInventory> tblUnserviceablePhysicalInventory { get; set; }
        public virtual DbSet<tblUserInRole> tblUserInRole { get; set; }
        public virtual DbSet<tblWebPages> tblWebPages { get; set; }
        public virtual DbSet<webpages_Membership> webpages_Membership { get; set; }
        public virtual DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public virtual DbSet<webpages_Roles> webpages_Roles { get; set; }
        public virtual DbSet<vwFirePreventionCounter> vwFirePreventionCounter { get; set; }
        public virtual DbSet<vwFireInvestigation> vwFireInvestigation { get; set; }
        public virtual DbSet<tblSuppliesInventory> tblSuppliesInventory { get; set; }
        public virtual DbSet<tblSuppliesInventoryOut> tblSuppliesInventoryOut { get; set; }
        public virtual DbSet<tblEmployeeAppointments> tblEmployeeAppointments { get; set; }
        public virtual DbSet<tblAfterFireOperationPersonnelsOnDuty> tblAfterFireOperationPersonnelsOnDuty { get; set; }
        public virtual DbSet<tblLogs> tblLogs { get; set; }
        public virtual DbSet<vwFees> vwFees { get; set; }
        public virtual DbSet<vwFirePreventionIOCounter> vwFirePreventionIOCounter { get; set; }
        public virtual DbSet<vwFirePreventionEstCounter> vwFirePreventionEstCounter { get; set; }
        public virtual DbSet<vwFPSSComplianceTable> vwFPSSComplianceTable { get; set; }
        public virtual DbSet<tblEligibilities> tblEligibilities { get; set; }
        public virtual DbSet<tblReligions> tblReligions { get; set; }
        public virtual DbSet<tblUnitSubStation> tblUnitSubStation { get; set; }
        public virtual DbSet<tblEmployeeWorkExperiences> tblEmployeeWorkExperiences { get; set; }
        public virtual DbSet<vwFSECFeesSummary> vwFSECFeesSummary { get; set; }
        public virtual DbSet<vwFSICFeesSummary> vwFSICFeesSummary { get; set; }
        public virtual DbSet<vwOtherFeesSummary> vwOtherFeesSummary { get; set; }
        public virtual DbSet<tblAfterFireOperations> tblAfterFireOperations { get; set; }
        public virtual DbSet<tblFireInvestigations> tblFireInvestigations { get; set; }
        public virtual DbSet<tblCityMunicipality> tblCityMunicipality { get; set; }
        public virtual DbSet<tblNonCommercialEstablishments> tblNonCommercialEstablishments { get; set; }
        public virtual DbSet<tblUnitsUserInRole> tblUnitsUserInRole { get; set; }
        public virtual DbSet<tblUserRoles> tblUserRoles { get; set; }
        public virtual DbSet<tblInspectionOrders> tblInspectionOrders { get; set; }
        public virtual DbSet<tblBPLOPayments> tblBPLOPayments { get; set; }
        public virtual DbSet<tblEmployeeVoluntaryWorks> tblEmployeeVoluntaryWorks { get; set; }
        public virtual DbSet<tblEmployeeSpecifyDesignation> tblEmployeeSpecifyDesignation { get; set; }
        public virtual DbSet<vwFeesByYearAndRegion> vwFeesByYearAndRegion { get; set; }
        public virtual DbSet<tblEmployees> tblEmployees { get; set; }
        public virtual DbSet<vwUsersInRole> vwUsersInRole { get; set; }
        public virtual DbSet<tblSpoiledOPS> tblSpoiledOPS { get; set; }
        public virtual DbSet<tblOtherFees> tblOtherFees { get; set; }
        public virtual DbSet<vwFireCodeRevenue> vwFireCodeRevenue { get; set; }
        public virtual DbSet<tblRanks> tblRanks { get; set; }
        public virtual DbSet<tblInspectionOrderViolations> tblInspectionOrderViolations { get; set; }
        public virtual DbSet<tblOtherViolations> tblOtherViolations { get; set; }
        public virtual DbSet<tblUnits> tblUnits { get; set; }
        public virtual DbSet<tblFSICApplication> tblFSICApplication { get; set; }
        public virtual DbSet<tblNoticeToComplyDeficiencies> tblNoticeToComplyDeficiencies { get; set; }
        public virtual DbSet<tblNoticeToCorrectViolationDeficiencies> tblNoticeToCorrectViolationDeficiencies { get; set; }
        public virtual DbSet<tblEstablishments> tblEstablishments { get; set; }
        public virtual DbSet<tblAbatementOrder> tblAbatementOrder { get; set; }
        public virtual DbSet<tblAbatementOrderDeficiencies> tblAbatementOrderDeficiencies { get; set; }
        public virtual DbSet<tblClosureOrder> tblClosureOrder { get; set; }
        public virtual DbSet<tblClosureOrderDeficiencies> tblClosureOrderDeficiencies { get; set; }
        public virtual DbSet<tblRegions> tblRegions { get; set; }
        public virtual DbSet<tblViolations> tblViolations { get; set; }
        public virtual DbSet<tblFSECApplication> tblFSECApplication { get; set; }
        public virtual DbSet<tblEmployeeServiceAppointments> tblEmployeeServiceAppointments { get; set; }
        public virtual DbSet<tblApplicationPayments> tblApplicationPayments { get; set; }
        public virtual DbSet<tblEmployeeTrainingPrograms> tblEmployeeTrainingPrograms { get; set; }
        public virtual DbSet<vwFeesByRegion> vwFeesByRegion { get; set; }
        public virtual DbSet<tblOtherClearances> tblOtherClearances { get; set; }
    
        public virtual ObjectResult<GetFees_Result> GetFees(Nullable<int> id, string restrictTo)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var restrictToParameter = restrictTo != null ?
                new ObjectParameter("restrictTo", restrictTo) :
                new ObjectParameter("restrictTo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFees_Result>("GetFees", idParameter, restrictToParameter);
        }
    
        public virtual ObjectResult<spGetSeniorityLinealListing_Result> spGetSeniorityLinealListing()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetSeniorityLinealListing_Result>("spGetSeniorityLinealListing");
        }
    }
}
