//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAfterFireOperationPersonnelsOnDuty
    {
        public int POD_Id { get; set; }
        public Nullable<int> POD_AFO_Id { get; set; }
        public Nullable<int> POD_Emp_Id { get; set; }
        public bool POD_InScene { get; set; }
        public string POD_Remarks { get; set; }
    
        public virtual tblAfterFireOperations tblAfterFireOperations { get; set; }
        public virtual tblEmployees tblEmployees { get; set; }
    }
}
