//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAbatementOrder
    {
        public int AO_Id { get; set; }
        public string Ref_AO_Id { get; set; }
        public System.DateTime AO_IssueDate { get; set; }
        public string AO_Est_Id { get; set; }
        public string AO_Ref_IO_Id { get; set; }
        public int AO_Created_Emp_Id { get; set; }
        public System.DateTime AO_CreatedDate { get; set; }
        public Nullable<int> AO_LastUpdate_Emp_Id { get; set; }
        public Nullable<System.DateTime> AO_LastUpdateDate { get; set; }
        public int AO_Status { get; set; }
        public string AO_Result_IO_Id { get; set; }
        public int AO_Unit_Id { get; set; }
        public bool IsSynced { get; set; }
    }
}
