//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAlarmTypes
    {
        public int AT_Id { get; set; }
        public string AT_Code { get; set; }
        public string AT_Description { get; set; }
        public int AT_Created_Emp_Id { get; set; }
        public System.DateTime AT_CreatedDate { get; set; }
        public Nullable<int> AT_LastUpdate_Emp_Id { get; set; }
        public Nullable<System.DateTime> AT_LastUpdateDate { get; set; }
    }
}
