//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAfterFireOperationRopesLadderUsed
    {
        public int RLU_Id { get; set; }
        public Nullable<int> RLU_AFO_Id { get; set; }
        public string RLU_Type { get; set; }
        public string RLU_Length { get; set; }
        public int RLU_Created_Emp_Id { get; set; }
        public System.DateTime RLU_CreatedDate { get; set; }
        public Nullable<int> RLU_LastUpdate_Emp_Id { get; set; }
        public Nullable<System.DateTime> RLU_LastUpdateDate { get; set; }
    
        public virtual tblAfterFireOperations tblAfterFireOperations { get; set; }
    }
}
