//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAfterFireOperationBreathingApparatusUsed
    {
        public int BAU_Id { get; set; }
        public Nullable<int> BAU_AFO_Id { get; set; }
        public string BAU_Number { get; set; }
        public string BAU_Type { get; set; }
        public string BAU_Quantity { get; set; }
        public int BAU_Created_Emp_Id { get; set; }
        public System.DateTime BAU_CreatedDate { get; set; }
        public Nullable<int> BAU_LastUpdate_Emp_Id { get; set; }
        public Nullable<System.DateTime> BAU_LastUpdateDate { get; set; }
    
        public virtual tblAfterFireOperations tblAfterFireOperations { get; set; }
    }
}
