//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAfterFireOperationOtherToolsUsed
    {
        public int OTU_Id { get; set; }
        public Nullable<int> OTU_AFO_Id { get; set; }
        public string OTU_Name { get; set; }
        public string OTU_Description { get; set; }
        public int OTU_Created_Emp_Id { get; set; }
        public System.DateTime OTU_CreatedDate { get; set; }
        public Nullable<int> OTU_LastUpdate_Emp_Id { get; set; }
        public Nullable<System.DateTime> OTU_LastUpdateDate { get; set; }
    
        public virtual tblAfterFireOperations tblAfterFireOperations { get; set; }
    }
}
