//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArticles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblArticles()
        {
            this.tblPhysicalInventory = new HashSet<tblPhysicalInventory>();
            this.tblSuppliesInventory = new HashSet<tblSuppliesInventory>();
        }
    
        public int Art_Id { get; set; }
        public string Art_Code { get; set; }
        public string Art_Name { get; set; }
        public int Art_Created_Emp_Id { get; set; }
        public System.DateTime Art_CreatedDate { get; set; }
        public Nullable<int> Art_LastUpdate_Emp_Id { get; set; }
        public Nullable<System.DateTime> Art_LastUpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPhysicalInventory> tblPhysicalInventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSuppliesInventory> tblSuppliesInventory { get; set; }
    }
}
