//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAbatementOrderDeficiencies
    {
        public int AOD_Id { get; set; }
        public string Ref_AOD_Id { get; set; }
        public string AOD_AO_Id { get; set; }
        public string AOD_Deficiency { get; set; }
        public string AOD_Compliance { get; set; }
        public string AOD_GracePeriod { get; set; }
        public bool AOD_Complied { get; set; }
        public string AOD_Remarks { get; set; }
        public int AOD_Unit_Id { get; set; }
        public bool IsSynced { get; set; }
        public Nullable<decimal> AOD_Fine { get; set; }
    }
}
