//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssetInventories
    {
        public int LA_Id { get; set; }
        public string LA_Item_Code { get; set; }
        public string LA_Item_Name { get; set; }
        public string LA_Item_Description { get; set; }
        public int LA_Item_Category { get; set; }
        public int LA_Item_Status { get; set; }
        public int LA_Unit_Id { get; set; }
        public int LA_Emp_Id { get; set; }
    
        public virtual tblUnits tblUnits { get; set; }
    }
}
