//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAfterInspectionReports
    {
        public int AIR_Id { get; set; }
        public int AIR_IO_Id { get; set; }
        public Nullable<System.DateTime> AIR_InspectionDate { get; set; }
        public int AIR_InspectionType { get; set; }
        public string AIR_InspectionType_Others { get; set; }
        public int AIR_Inspector_Emp_Id { get; set; }
    }
}
