//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAfterFireOperationExtinguishingAgentsUsed
    {
        public int EAU_Id { get; set; }
        public int EAU_AFO_Id { get; set; }
        public string EAU_Number { get; set; }
        public string EAU_Type { get; set; }
        public string EAU_Quantity { get; set; }
        public int EAU_Created_Emp_Id { get; set; }
        public System.DateTime EAU_CreatedDate { get; set; }
        public Nullable<int> EAU_LastUpdate_Emp_Id { get; set; }
        public Nullable<System.DateTime> EAU_LastUpdateDate { get; set; }
    
        public virtual tblAfterFireOperations tblAfterFireOperations { get; set; }
    }
}
