//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBPLOPayments
    {
        public int BPLOP_Id { get; set; }
        public string Ref_BPLOP_Id { get; set; }
        public string BPLOP_App_Id { get; set; }
        public decimal BPLOP_PayAmount { get; set; }
        public System.DateTime BPLOP_PayDate { get; set; }
        public int BPLOP_Created_Emp_Id { get; set; }
        public System.DateTime BPLOP_CreatedDate { get; set; }
        public string BPLOP_BasisOfAmountPaid { get; set; }
        public int BPLOP_Unit_Id { get; set; }
        public bool IsSynced { get; set; }
    }
}
