//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCityMunicipality
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCityMunicipality()
        {
            this.tblFireRecords = new HashSet<tblFireRecords>();
            this.tblPopulations = new HashSet<tblPopulations>();
            this.tblUnits = new HashSet<tblUnits>();
        }
    
        public int Municipality_Id { get; set; }
        public int Municipality_Province_Id { get; set; }
        public string Municipality_NSCB { get; set; }
        public string Municipality_Name { get; set; }
        public Nullable<int> Municipality_Classification { get; set; }
        public Nullable<decimal> Municipality_LandArea { get; set; }
        public Nullable<decimal> Municipality_PopulationDensity { get; set; }
        public Nullable<int> Municipality_IncomeClass { get; set; }
        public string Municipality_FireFightingCapability { get; set; }
        public Nullable<int> Municipality_Urban { get; set; }
        public Nullable<int> Municipality_Rural { get; set; }
        public Nullable<int> Municipality_Barangays { get; set; }
        public Nullable<int> Municipality_CSUPT { get; set; }
        public Nullable<int> Municipality_SSUPT { get; set; }
        public Nullable<int> Municipality_SUPT { get; set; }
        public Nullable<int> Municipality_CINSP { get; set; }
        public Nullable<int> Municipality_SINSP { get; set; }
        public Nullable<int> Municipality_INSP { get; set; }
        public Nullable<int> Municipality_SFO4 { get; set; }
        public Nullable<int> Municipality_SFO3 { get; set; }
        public Nullable<int> Municipality_SFO2 { get; set; }
        public Nullable<int> Municipality_SFO1 { get; set; }
        public Nullable<int> Municipality_FO3 { get; set; }
        public Nullable<int> Municipality_FO2 { get; set; }
        public Nullable<int> Municipality_FO1 { get; set; }
        public Nullable<int> Municipality_UPersonnel { get; set; }
        public Nullable<int> Municipality_NUP { get; set; }
        public Nullable<int> Municipality_Hydrant_Functional { get; set; }
        public Nullable<int> Municipality_Hydrant_NonFunctional { get; set; }
        public Nullable<int> Municipality_Hydrant_UnderRepair { get; set; }
        public Nullable<int> Municipality_Type { get; set; }
        public Nullable<bool> Municipality_WithBuilding { get; set; }
        public Nullable<int> Municipality_SCBA_Serviceable { get; set; }
        public Nullable<int> Municipality_SCBA_ServiceableForReplacement { get; set; }
        public Nullable<int> Municipality_FireCoat_Serviceable { get; set; }
        public Nullable<int> Municipality_FireCoat_ServiceableForReplacement { get; set; }
        public Nullable<int> Municipality_Trouser_Serviceable { get; set; }
        public Nullable<int> Municipality_Trouser_ServiceableForReplacement { get; set; }
        public Nullable<int> Municipality_Boots_Serviceable { get; set; }
        public Nullable<int> Municipality_Boots_ServiceableForReplacement { get; set; }
        public Nullable<int> Municipality_Gloves_Serviceable { get; set; }
        public Nullable<int> Municipality_Gloves_ServiceableForReplacement { get; set; }
        public Nullable<int> Municipality_Helmet_Serviceable { get; set; }
        public Nullable<int> Municipality_Helmet_ServiceableForReplacement { get; set; }
        public Nullable<int> Municipality_FireHose15_Serviceable { get; set; }
        public Nullable<int> Municipality_FireHose15_ServiceableForReplacement { get; set; }
        public Nullable<int> Municipality_FireHose25_Serviceable { get; set; }
        public Nullable<int> Municipality_FireHose25_ServiceableForReplacement { get; set; }
        public Nullable<int> Municipality_FireNozzle15_Serviceable { get; set; }
        public Nullable<int> Municipality_FireNozzle15_ServiceableForReplacement { get; set; }
        public Nullable<int> Municipality_FireNozzle25_Serviceable { get; set; }
        public Nullable<int> Municipality_FireNozzle25_ServiceableForReplacement { get; set; }
    
        public virtual tblProvinces tblProvinces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFireRecords> tblFireRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPopulations> tblPopulations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUnits> tblUnits { get; set; }
    }
}
