//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeLeaveRecords
    {
        public int ELR_Id { get; set; }
        public int ELR_Emp_Id { get; set; }
        public int ELR_LeaveType { get; set; }
        public System.DateTime ELR_StartDate { get; set; }
        public System.DateTime ELR_EndDate { get; set; }
        public decimal ELR_TotalDays { get; set; }
        public bool ELR_WithPay { get; set; }
        public string ELR_Remarks { get; set; }
        public System.DateTime ELR_InputDate { get; set; }
        public int ELR_Input_Emp_Id { get; set; }
        public int ELR_ChargeTo { get; set; }
    
        public virtual tblEmployees tblEmployees { get; set; }
        public virtual tblEmployees tblEmployees1 { get; set; }
    }
}
