//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeServiceAppointments
    {
        public int ESA_Id { get; set; }
        public string ESA_PosDesignation { get; set; }
        public int ESA_Rank { get; set; }
        public string ESA_Appt_Status { get; set; }
        public int ESA_SalaryGrade { get; set; }
        public decimal ESA_SalaryAmt { get; set; }
        public int ESA_JobFuncCategory { get; set; }
        public Nullable<int> ESA_JobFuncSubCategory { get; set; }
        public int ESA_ApptType { get; set; }
        public System.DateTime ESA_ApptDate { get; set; }
        public Nullable<System.DateTime> ESA_EndDate { get; set; }
        public string ESA_Office_Entity { get; set; }
        public int ESA_Emp_Id { get; set; }
        public int ESA_DutyStatus { get; set; }
        public string ESA_LeaveWithoutPay { get; set; }
        public string ESA_OtherRank { get; set; }
        public string ESA_Authority { get; set; }
    
        public virtual tblEmployees tblEmployees { get; set; }
    }
}
