//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeAppointments
    {
        public int EA_Id { get; set; }
        public int EA_Emp_Id { get; set; }
        public int EA_Rank_Id { get; set; }
        public int EA_AppoitmentStatus { get; set; }
        public string EA_ItemNumber { get; set; }
        public int EA_AppoitmentNature { get; set; }
        public string EA_PositionVacatedBy { get; set; }
        public string EA_AppointingAuthority { get; set; }
        public System.DateTime EA_AppointmentDate { get; set; }
        public string EA_AttestingAuthority { get; set; }
        public string EA_AttestingAuthorityDesignation { get; set; }
        public System.DateTime EA_AttestmentDate { get; set; }
        public Nullable<int> EA_NonRenewalReason { get; set; }
        public int EA_Created_Emp_Id { get; set; }
        public System.DateTime EA_CreatedDate { get; set; }
        public Nullable<int> EA_LastUpdate_Emp_Id { get; set; }
        public Nullable<System.DateTime> EA_LastUpdateDate { get; set; }
    
        public virtual tblEmployees tblEmployees { get; set; }
        public virtual tblEmployees tblEmployees1 { get; set; }
        public virtual tblEmployees tblEmployees2 { get; set; }
        public virtual tblRanks tblRanks { get; set; }
    }
}
