//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeDutyStatusUpdates
    {
        public int EDSU_Id { get; set; }
        public System.DateTime EDSU_StartDate { get; set; }
        public Nullable<System.DateTime> EDSU_EndDate { get; set; }
        public int EDSU_DutyStatus { get; set; }
        public string EDSU_DutyStatus_Remarks { get; set; }
        public int EDSU_Emp_Id { get; set; }
        public System.DateTime EDSU_Create_Date { get; set; }
        public string EDSU_Create_Emp_Id { get; set; }
    }
}
