//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEstablishments
    {
        public int Est_Id { get; set; }
        public string Ref_Est_Id { get; set; }
        public string Est_MP_Number { get; set; }
        public string Est_BusinessName { get; set; }
        public string Est_BusinessTradeName { get; set; }
        public string Est_BusinessPermitNumber { get; set; }
        public string Est_NatureOfBusiness { get; set; }
        public string Est_BusinessAddress { get; set; }
        public string Est_BuildingConstruction { get; set; }
        public string Est_OwnerName { get; set; }
        public string Est_PhoneFaxNumber { get; set; }
        public string Est_MobileNumber { get; set; }
        public int Est_OccupancyType { get; set; }
        public Nullable<int> Est_OwnershipType { get; set; }
        public string Est_LandArea { get; set; }
        public Nullable<int> Est_NumberOfFloor { get; set; }
        public string Est_FloorArea { get; set; }
        public string Est_TotalFloorArea { get; set; }
        public Nullable<int> Est_OccupantsEmployeeNumber { get; set; }
        public int Est_RegistrationStatus { get; set; }
        public int Est_HazardType { get; set; }
        public int Est_EstablishmentStatus { get; set; }
        public int Est_Unit_Id { get; set; }
        public int Est_Created_Emp_Id { get; set; }
        public System.DateTime Est_CreatedDate { get; set; }
        public Nullable<int> Est_LastUpdate_Emp_Id { get; set; }
        public Nullable<System.DateTime> Est_LastUpdateDate { get; set; }
        public string Est_AuthorizedRepresentative { get; set; }
        public bool IsSynced { get; set; }
        public string Est_BuildingType { get; set; }
        public Nullable<System.DateTime> Est_ExpiryDate { get; set; }
        public Nullable<bool> Est_IsPEZA { get; set; }
    
        public virtual tblUnits tblUnits { get; set; }
    }
}
