//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeReferences
    {
        public int ER_Id { get; set; }
        public string ER_FullName { get; set; }
        public string ER_Address { get; set; }
        public string ER_PhoneNumber { get; set; }
        public int ER_Emp_Id { get; set; }
    
        public virtual tblEmployees tblEmployees { get; set; }
    }
}
