//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeEducationalBackground
    {
        public int EEB_Id { get; set; }
        public int EEB_EducType { get; set; }
        public string EEB_SchoolName { get; set; }
        public string EEB_DegreeCourse { get; set; }
        public string EEB_GraduateYear { get; set; }
        public string EEB_HighestLevel { get; set; }
        public string EEB_StartDate { get; set; }
        public string EEB_EndDate { get; set; }
        public string EEB_Awards { get; set; }
        public int EEB_Emp_Id { get; set; }
    
        public virtual tblEmployees tblEmployees { get; set; }
    }
}
