//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFireRecords
    {
        public int Fire_Id { get; set; }
        public int Fire_Municipality_Id { get; set; }
        public string Fire_Year { get; set; }
        public Nullable<int> Fire_Incidents { get; set; }
        public Nullable<int> Fire_Injuries { get; set; }
        public Nullable<int> Fire_Deaths { get; set; }
        public Nullable<decimal> Fire_Damages { get; set; }
    
        public virtual tblCityMunicipality tblCityMunicipality { get; set; }
    }
}
