//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFireSuppression
    {
        public int FS_Id { get; set; }
        public string FS_FilePath { get; set; }
        public string FS_ReportedBy { get; set; }
        public string FS_MobileNo { get; set; }
        public string FS_Remarks { get; set; }
        public Nullable<System.DateTime> FS_DateCreated { get; set; }
        public string FS_GeoLong { get; set; }
        public string FS_GeoLat { get; set; }
    }
}
