//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFSECApplication
    {
        public int FSEC_App_Id { get; set; }
        public System.DateTime FSEC_ApplicationDate { get; set; }
        public int FSEC_EstablishmentType { get; set; }
        public string FSEC_Est_Id { get; set; }
        public Nullable<bool> FSEC_BuildingPlans { get; set; }
        public Nullable<bool> FSEC_Specification { get; set; }
        public Nullable<bool> FSEC_BOM { get; set; }
        public Nullable<bool> FSEC_LocationClearance { get; set; }
        public Nullable<bool> FSEC_ElectricalPermit { get; set; }
        public Nullable<bool> FSEC_ElectricalPlans { get; set; }
        public Nullable<bool> FSEC_ElectricalBOM { get; set; }
        public Nullable<bool> FSEC_TotalConnectedLoad { get; set; }
        public Nullable<bool> FSEC_MechanicalPermit { get; set; }
        public Nullable<bool> FSEC_MechanicalPlans { get; set; }
        public Nullable<bool> FSEC_MechanicalBOM { get; set; }
        public int FSEC_Status { get; set; }
        public string FSEC_Remarks { get; set; }
        public Nullable<decimal> FSEC_ConstructionTax { get; set; }
        public Nullable<decimal> FSEC_InstallationClearance { get; set; }
        public Nullable<decimal> FSEC_HotWorkClearance { get; set; }
        public Nullable<decimal> FSEC_OtherFee { get; set; }
        public Nullable<int> FSEC_Evaluator_Emp_Id { get; set; }
        public Nullable<int> FSEC_Assesor_Emp_Id { get; set; }
        public Nullable<int> FSEC_Collector_Emp_Id { get; set; }
        public Nullable<int> FSEC_ForReleasing_Emp_Id { get; set; }
        public Nullable<int> FSEC_Released_Emp_Id { get; set; }
        public Nullable<System.DateTime> FSEC_Evaluated_Date { get; set; }
        public Nullable<System.DateTime> FSEC_Assesed_Date { get; set; }
        public Nullable<System.DateTime> FSEC_Collected_Date { get; set; }
        public Nullable<System.DateTime> FSEC_ForReleased_Date { get; set; }
        public Nullable<System.DateTime> FSEC_Released_Date { get; set; }
        public string FSEC_OPS_Number { get; set; }
        public string Ref_FSEC_App_Id { get; set; }
        public bool IsSynced { get; set; }
        public int FSEC_Unit_Id { get; set; }
        public Nullable<System.DateTime> FSEC_PlanEvaluated_Date { get; set; }
        public Nullable<int> FSEC_PlanEvaluator_Emp_Id { get; set; }
        public string FSEC_PlanEvaluation_Remarks { get; set; }
        public Nullable<System.DateTime> FSEC_ChiefFSES_Date { get; set; }
        public Nullable<int> FSEC_ChiefFSES_Emp_Id { get; set; }
        public string FSEC_ChiefFSES_Remarks { get; set; }
        public Nullable<System.DateTime> FSEC_Mashall_Date { get; set; }
        public Nullable<int> FSEC_Marshall_Emp_Id { get; set; }
        public string FSEC_Marshall_Remarks { get; set; }
        public Nullable<bool> FSEC_IsApprovePlanEvaluated { get; set; }
        public Nullable<bool> FSEC_IsApproveChiefFSES { get; set; }
        public Nullable<bool> FSEC_IsApproveMarshall { get; set; }
        public string FSEC_Number { get; set; }
        public string FSEC_Disapproval_Number { get; set; }
        public string FSEC_ClaimStub_Number { get; set; }
        public Nullable<bool> FSEC_IsManual { get; set; }
        public Nullable<bool> FSEC_BPS1 { get; set; }
        public Nullable<bool> FSEC_BPS2 { get; set; }
        public Nullable<bool> FSEC_BPS3 { get; set; }
        public Nullable<bool> FSEC_BPS4 { get; set; }
        public Nullable<bool> FSEC_BPS5 { get; set; }
        public Nullable<bool> FSEC_BPS6 { get; set; }
        public Nullable<bool> FSEC_BPS7 { get; set; }
        public Nullable<bool> FSEC_BPS8 { get; set; }
        public Nullable<decimal> FSEC_ValueOfBuilding { get; set; }
    }
}
