//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFSICApplication
    {
        public int FSIC_App_Id { get; set; }
        public System.DateTime FSIC_ApplicationDate { get; set; }
        public Nullable<int> FSIC_ApplicationType { get; set; }
        public Nullable<int> FSIC_ApplicationSubType { get; set; }
        public int FSIC_TaxYear { get; set; }
        public string FSIC_BillingNumber { get; set; }
        public string FSIC_Est_Id { get; set; }
        public Nullable<int> FSIC_Requirement1 { get; set; }
        public Nullable<int> FSIC_Requirement2 { get; set; }
        public Nullable<int> FSIC_Requirement3 { get; set; }
        public Nullable<int> FSIC_Requirement4 { get; set; }
        public Nullable<int> FSIC_Requirement5 { get; set; }
        public Nullable<int> FSIC_Requirement6 { get; set; }
        public Nullable<int> FSIC_Requirement7 { get; set; }
        public Nullable<int> FSIC_Requirement8 { get; set; }
        public Nullable<int> FSIC_Requirement9 { get; set; }
        public Nullable<int> FSIC_Requirement10 { get; set; }
        public Nullable<decimal> FSIC_ConstructionTax { get; set; }
        public Nullable<decimal> FSIC_RealtyTax { get; set; }
        public Nullable<decimal> FSIC_PremiumTax { get; set; }
        public Nullable<decimal> FSIC_SalesTax { get; set; }
        public Nullable<decimal> FSIC_ProceedsTax { get; set; }
        public Nullable<decimal> FSIC_FireSafetyInspectionFee { get; set; }
        public Nullable<decimal> FSIC_StorageClearanceFee { get; set; }
        public Nullable<decimal> FSIC_ConveyanceClearanceFee { get; set; }
        public Nullable<decimal> FSIC_InstallationClearanceFee { get; set; }
        public Nullable<decimal> FSIC_FireCodeAdminFine { get; set; }
        public Nullable<decimal> FSIC_OtherFee { get; set; }
        public int FSIC_Status { get; set; }
        public string FSIC_Remarks { get; set; }
        public Nullable<int> FSIC_Evaluator_Emp_Id { get; set; }
        public Nullable<System.DateTime> FSIC_Evaluated_Date { get; set; }
        public Nullable<int> FSIC_Assesor_Emp_Id { get; set; }
        public Nullable<System.DateTime> FSIC_Assesed_Date { get; set; }
        public Nullable<int> FSIC_Collector_Emp_Id { get; set; }
        public Nullable<System.DateTime> FSIC_Collected_Date { get; set; }
        public Nullable<int> FSIC_ForReleasing_Emp_Id { get; set; }
        public Nullable<System.DateTime> FSIC_ForReleased_Date { get; set; }
        public Nullable<int> FSIC_Released_Emp_Id { get; set; }
        public Nullable<System.DateTime> FSIC_Released_Date { get; set; }
        public Nullable<System.DateTime> FSIC_Issue_Date { get; set; }
        public string FSIC_Issue_No { get; set; }
        public string FSIC_OPS_Number { get; set; }
        public string Ref_FSIC_App_Id { get; set; }
        public bool IsSynced { get; set; }
        public int FSIC_Unit_Id { get; set; }
        public Nullable<int> FSIC_ChiefFSES_Emp_Id { get; set; }
        public Nullable<int> FSIC_Marshall_Emp_Id { get; set; }
        public Nullable<System.DateTime> FSIC_ChiefFSES_Date { get; set; }
        public Nullable<System.DateTime> FSIC_Marshall_Date { get; set; }
        public Nullable<int> FSIC_AIR_ChiefFSES_Emp_Id { get; set; }
        public Nullable<int> FSIC_AIR_Marshall_Emp_Id { get; set; }
        public Nullable<System.DateTime> FSIC_AIR_ChiefFSES_Date { get; set; }
        public Nullable<System.DateTime> FSIC_AIR_Marshall_Date { get; set; }
        public Nullable<bool> FSIC_IsApproveChiefFSES { get; set; }
        public Nullable<bool> FSIC_IsApproveMarshall { get; set; }
        public Nullable<bool> FSIC_AIR_IsApproveChiefFSES { get; set; }
        public Nullable<bool> FSIC_AIR_IsApproveMarshall { get; set; }
        public Nullable<System.DateTime> FSIC_Approve_Marshall_Date { get; set; }
        public Nullable<System.DateTime> FSIC_Approve_ChiefFSES_Date { get; set; }
        public Nullable<System.DateTime> FSIC_AIR_Approve_Marshall_Date { get; set; }
        public Nullable<System.DateTime> FSIC_AIR_Approve_ChiefFSES_Date { get; set; }
        public string FSIC_Number { get; set; }
        public string FSIC_ClaimStub_Number { get; set; }
        public Nullable<int> FSIC_BusinessType { get; set; }
    }
}
