//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInspectionOrderActions
    {
        public int IOA_Id { get; set; }
        public string IOA_ActionName { get; set; }
        public Nullable<int> IOA_Remark_Id { get; set; }
        public Nullable<int> IOA_Est_Status { get; set; }
    }
}
