//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIndexTypes
    {
        public int IT_Id { get; set; }
        public string IT_Code { get; set; }
        public string IT_Description { get; set; }
        public int IT_Created_Emp_Id { get; set; }
        public System.DateTime IT_CreatedDate { get; set; }
        public Nullable<int> IT_LastUpdate_Emp_Id { get; set; }
        public Nullable<System.DateTime> IT_LastUpdateDate { get; set; }
    }
}
