//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIncidentStatus
    {
        public int IS_Id { get; set; }
        public string IS_Code { get; set; }
        public string IS_Description { get; set; }
        public int IS_Created_Emp_Id { get; set; }
        public System.DateTime IS_CreatedDate { get; set; }
        public Nullable<int> IS_LastUpdate_Emp_Id { get; set; }
        public Nullable<System.DateTime> IS_LastUpdateDate { get; set; }
    }
}
