//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInspectionOrders
    {
        public int IO_Id { get; set; }
        public string Ref_IO_Id { get; set; }
        public string IO_Number { get; set; }
        public System.DateTime IO_IssueDate { get; set; }
        public int IO_Approval_Emp_Id { get; set; }
        public Nullable<System.DateTime> IO_ApprovalDate { get; set; }
        public Nullable<int> IO_InspectionType { get; set; }
        public Nullable<System.DateTime> IO_InspectionDate { get; set; }
        public string IO_Est_Id { get; set; }
        public Nullable<int> IO_Est_RegistrationStatus { get; set; }
        public Nullable<int> IO_Est_HazardType { get; set; }
        public Nullable<int> IO_Est_EstablishmentStatus { get; set; }
        public Nullable<int> IO_Est_OccupancyType { get; set; }
        public string IO_Findings { get; set; }
        public Nullable<int> IO_Remarks { get; set; }
        public string IO_Remarks_Others { get; set; }
        public Nullable<int> IO_ActionTaken { get; set; }
        public Nullable<System.DateTime> IO_ActionTakenDate { get; set; }
        public string IO_Est_Details_String { get; set; }
        public int IO_Status { get; set; }
        public int IO_Created_Emp_Id { get; set; }
        public System.DateTime IO_CreatedDate { get; set; }
        public Nullable<int> IO_LastUpdate_Emp_Id { get; set; }
        public Nullable<System.DateTime> IO_LastUpdateDate { get; set; }
        public int IO_Unit_Id { get; set; }
        public bool IsSynced { get; set; }
        public byte[] IO_AIR { get; set; }
        public string IO_AIR_Ext { get; set; }
        public Nullable<int> IO_ApprovalMarshall_Emp_Id { get; set; }
        public Nullable<int> IO_ApprovalChiefFSES_Emp_Id { get; set; }
        public Nullable<int> IO_Approval_AIR_Marshall_Emp_Id { get; set; }
        public Nullable<int> IO_Approval_AIR_ChiefFSES_Emp_Id { get; set; }
    
        public virtual tblUnits tblUnits { get; set; }
    }
}
