//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInspectionOrderInspectors
    {
        public int Insp_Id { get; set; }
        public string Ref_Insp_Id { get; set; }
        public string Insp_IO_Id { get; set; }
        public int Insp_Emp_Id { get; set; }
        public int Insp_Unit_Id { get; set; }
        public bool IsSynced { get; set; }
    }
}
