//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInventoryGroups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblInventoryGroups()
        {
            this.tblPhysicalInventory = new HashSet<tblPhysicalInventory>();
        }
    
        public int IG_Id { get; set; }
        public string IG_Code { get; set; }
        public string IG_Description { get; set; }
        public int IG_Created_Emp_Id { get; set; }
        public System.DateTime IG_CreatedDate { get; set; }
        public Nullable<int> IG_LastUpdate_Emp_Id { get; set; }
        public Nullable<System.DateTime> IG_LastUpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPhysicalInventory> tblPhysicalInventory { get; set; }
    }
}
