//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJobFunctions
    {
        public int JobFunc_Id { get; set; }
        public string JobFunc_Code { get; set; }
        public string JobFunc_Name { get; set; }
    }
}
