//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLogs
    {
        public int Log_Id { get; set; }
        public int Log_Emp_Id { get; set; }
        public string Log_Remarks { get; set; }
        public System.DateTime Log_UpdatedDate { get; set; }
        public int Log_Updated_Emp_Id { get; set; }
    }
}
