//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMedical
    {
        public int Med_Id { get; set; }
        public Nullable<int> Emp_Id { get; set; }
        public Nullable<int> Med_CategoryId { get; set; }
        public string Med_Details_Json { get; set; }
    }
}
