//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNoticeToComplyDeficiencies
    {
        public int NTCD_Id { get; set; }
        public string Ref_NTCD_Id { get; set; }
        public string NTCD_NTC_Id { get; set; }
        public string NTCD_Deficiency { get; set; }
        public string NTCD_Compliance { get; set; }
        public string NTCD_GracePeriod { get; set; }
        public bool NTCD_Complied { get; set; }
        public string NTCD_Remarks { get; set; }
        public int NTCD_Unit_Id { get; set; }
        public Nullable<decimal> NTCD_Fine { get; set; }
    }
}
