//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNoticeToCorrectViolationDeficiencies
    {
        public int NTCVD_Id { get; set; }
        public string Ref_NTCVD_Id { get; set; }
        public string NTCVD_NTCV_Id { get; set; }
        public string NTCVD_Deficiency { get; set; }
        public string NTCVD_Compliance { get; set; }
        public string NTCVD_GracePeriod { get; set; }
        public bool NTCVD_Complied { get; set; }
        public string NTCVD_Remarks { get; set; }
        public int NTCVD_Unit_Id { get; set; }
        public Nullable<decimal> NTCVD_Fine { get; set; }
    }
}
