//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNoticeToCorrectViolations
    {
        public int NTCV_Id { get; set; }
        public string Ref_NTCV_Id { get; set; }
        public System.DateTime NTCV_IssueDate { get; set; }
        public string NTCV_Est_Id { get; set; }
        public string NTCV_Ref_IO_Id { get; set; }
        public int NTCV_Created_Emp_Id { get; set; }
        public System.DateTime NTCV_CreatedDate { get; set; }
        public Nullable<int> NTCV_LastUpdate_Emp_Id { get; set; }
        public Nullable<System.DateTime> NTCV_LastUpdateDate { get; set; }
        public int NTCV_Status { get; set; }
        public string NTCV_Result_IO_Id { get; set; }
        public int NTCV_Unit_Id { get; set; }
        public bool IsSynced { get; set; }
    }
}
