//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNonCommercialEstablishments
    {
        public int NCE_Id { get; set; }
        public string Ref_NCE_Id { get; set; }
        public string NCE_OwnerName { get; set; }
        public string NCE_ConstructionAddress { get; set; }
        public string NCE_AuthorizedRepresentative { get; set; }
        public string NCE_ContactNumber { get; set; }
        public int NCE_Unit_Id { get; set; }
        public int NCE_Created_Emp_Id { get; set; }
        public System.DateTime NCE_CreatedDate { get; set; }
        public int NCE_LastUpdate_Emp_Id { get; set; }
        public System.DateTime NCE_LastUpdateDate { get; set; }
        public bool IsSynced { get; set; }
        public string NCE_NatureOfConstruction { get; set; }
    }
}
