//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOtherVehicles
    {
        public int Vehicle_Id { get; set; }
        public int Vehicle_UnitId { get; set; }
        public Nullable<int> Vehicle_SubStationId { get; set; }
        public string Vehicle_Id_Code { get; set; }
        public Nullable<int> Vehicle_Model { get; set; }
        public Nullable<int> Vehicle_Owner { get; set; }
        public Nullable<int> Vehicle_Status { get; set; }
        public Nullable<int> Vehicle_Type { get; set; }
        public string Vehicle_PlateNumber { get; set; }
        public string Vehicle_EngineNumber { get; set; }
        public string Vehicle_ChasisNumber { get; set; }
        public Nullable<decimal> Vehicle_AcquisitionCost { get; set; }
        public Nullable<int> Vehicle_ManufactureDate { get; set; }
        public Nullable<int> Vehicle_AcquisitionDate { get; set; }
        public string Vehicle_Remarks { get; set; }
        public string Vehicle_FrontView { get; set; }
        public string Vehicle_RearView { get; set; }
        public string Vehicle_LeftView { get; set; }
        public string Vehicle_RightView { get; set; }
        public Nullable<int> Vehicle_CreatedBy { get; set; }
        public Nullable<System.DateTime> Vehicle_CreatedDate { get; set; }
        public Nullable<int> Vehicle_ModifiedBy { get; set; }
        public Nullable<System.DateTime> Vehicle_ModifiedDate { get; set; }
    
        public virtual tblUnitSubStation tblUnitSubStation { get; set; }
        public virtual tblUnits tblUnits { get; set; }
    }
}
