//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOtherFees
    {
        public int OF_Id { get; set; }
        public Nullable<System.DateTime> OF_ApplicationDate { get; set; }
        public int OF_EstablishmentType { get; set; }
        public string OF_Est_Id { get; set; }
        public string OF_OPS_Number { get; set; }
        public int OF_CollectionType { get; set; }
        public Nullable<decimal> OF_Fee { get; set; }
        public int OF_Status { get; set; }
        public string OF_Remarks { get; set; }
        public Nullable<int> OF_Evaluator_Emp_Id { get; set; }
        public Nullable<System.DateTime> OF_Evaluated_Date { get; set; }
        public Nullable<int> OF_Assesor_Emp_Id { get; set; }
        public Nullable<System.DateTime> OF_Assesed_Date { get; set; }
        public Nullable<int> OF_Collector_Emp_Id { get; set; }
        public Nullable<System.DateTime> OF_Collected_Date { get; set; }
        public Nullable<int> OF_ForReleasing_Emp_Id { get; set; }
        public Nullable<System.DateTime> OF_ForReleased_Date { get; set; }
        public Nullable<int> OF_Released_Emp_Id { get; set; }
        public Nullable<System.DateTime> OF_Released_Date { get; set; }
        public Nullable<System.DateTime> OF_Issue_Date { get; set; }
        public string OF_Issue_No { get; set; }
        public string Ref_OF_Id { get; set; }
        public int OF_Unit_Id { get; set; }
        public bool IsSynced { get; set; }
        public string OF_Number { get; set; }
        public string OF_ClaimStub_Number { get; set; }
        public Nullable<System.DateTime> OF_ChiefFSES_Date { get; set; }
        public Nullable<int> OF_ChiefFSES_Emp_Id { get; set; }
        public string OF_ChiefFSES_Remarks { get; set; }
        public Nullable<System.DateTime> OF_Marshal_Date { get; set; }
        public Nullable<int> OF_Marshal_Emp_Id { get; set; }
        public string OF_Marshal_Remarks { get; set; }
        public Nullable<bool> OF_IsApproveChiefFSES { get; set; }
        public Nullable<bool> OF_IsApproveMarshal { get; set; }
    }
}
