//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOPSSeries
    {
        public int OPS_Id { get; set; }
        public string Ref_OPS_Id { get; set; }
        public System.DateTime OPS_Issue_Date { get; set; }
        public long OPS_StartSeries { get; set; }
        public long OPS_EndSeries { get; set; }
        public int OPS_Created_Emp_Id { get; set; }
        public System.DateTime OPS_CreatedDate { get; set; }
        public Nullable<int> OPS_LastUpdate_Emp_Id { get; set; }
        public Nullable<System.DateTime> OPS_LastUpdateDate { get; set; }
        public int OPS_Unit_Id { get; set; }
        public bool IsSynced { get; set; }
    }
}
