//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblORSeries
    {
        public int OR_Id { get; set; }
        public string Ref_OR_Id { get; set; }
        public System.DateTime OR_Issue_Date { get; set; }
        public long OR_StartSeries { get; set; }
        public long OR_EndSeries { get; set; }
        public int OR_Created_Emp_Id { get; set; }
        public System.DateTime OR_CreatedDate { get; set; }
        public Nullable<int> OR_LastUpdate_Emp_Id { get; set; }
        public Nullable<System.DateTime> OR_LastUpdateDate { get; set; }
        public int OR_Unit_Id { get; set; }
        public bool IsSynced { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
