//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPhysicalInventory
    {
        public int PI_Id { get; set; }
        public int PI_Dir_Id { get; set; }
        public int PI_IG_Id { get; set; }
        public int PI_Art_Id { get; set; }
        public int PI_Unit_Id { get; set; }
        public string PI_Description { get; set; }
        public string PI_PropertyNumber { get; set; }
        public string PI_StockNumber { get; set; }
        public string PI_UnitOfMeasure { get; set; }
        public Nullable<System.DateTime> PI_DateAcquired { get; set; }
        public Nullable<decimal> PI_UnitValue { get; set; }
        public string PI_ARENumber { get; set; }
        public string PI_ICSNUmber { get; set; }
        public Nullable<int> PI_Emp_Id { get; set; }
        public string PI_Remarks { get; set; }
        public string PI_Office { get; set; }
        public int PI_Created_Emp_Id { get; set; }
        public System.DateTime PI_CreatedDate { get; set; }
        public Nullable<int> PI_LastUpdate_Emp_Id { get; set; }
        public Nullable<System.DateTime> PI_LastUpdateDate { get; set; }
        public Nullable<int> PI_UPI_Id { get; set; }
        public bool PI_IsDeleted { get; set; }
    
        public virtual tblArticles tblArticles { get; set; }
        public virtual tblDirectorates tblDirectorates { get; set; }
        public virtual tblInventoryGroups tblInventoryGroups { get; set; }
        public virtual tblUnserviceablePhysicalInventory tblUnserviceablePhysicalInventory { get; set; }
        public virtual tblEmployees tblEmployees { get; set; }
        public virtual tblUnits tblUnits { get; set; }
    }
}
