//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPopulations
    {
        public int Population_Id { get; set; }
        public int Population_Municipality_Id { get; set; }
        public string Population_Year { get; set; }
        public Nullable<int> Population_Count { get; set; }
    
        public virtual tblCityMunicipality tblCityMunicipality { get; set; }
    }
}
