//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRanks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblRanks()
        {
            this.tblEmployeeAppointments = new HashSet<tblEmployeeAppointments>();
            this.tblEmployees = new HashSet<tblEmployees>();
        }
    
        public int Rank_Id { get; set; }
        public string Rank_Name { get; set; }
        public int Rank_DBM_Authorized { get; set; }
        public Nullable<int> Rank_CreatedBy { get; set; }
        public Nullable<System.DateTime> Rank_CreatedDate { get; set; }
        public Nullable<int> Rank_UpdatedBy { get; set; }
        public Nullable<System.DateTime> Rank_UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeAppointments> tblEmployeeAppointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployees> tblEmployees { get; set; }
    }
}
