//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRoleAccess
    {
        public int RA_ID { get; set; }
        public int RA_Role_ID { get; set; }
        public int RA_PageSecurityID { get; set; }
    
        public virtual tblUserRoles tblUserRoles { get; set; }
    }
}
