//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSpoiledOR
    {
        public int SOR_Id { get; set; }
        public string Ref_SOR_Id { get; set; }
        public long SOR_Number { get; set; }
        public int SOR_Created_Emp_Id { get; set; }
        public System.DateTime SOR_CreatedDate { get; set; }
        public int SOR_Unit_Id { get; set; }
        public bool IsSynced { get; set; }
    }
}
