//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUnitDeposits
    {
        public int Dep_Id { get; set; }
        public string Ref_Dep_Id { get; set; }
        public int Dep_Unit_Id { get; set; }
        public string Dep_LC_No { get; set; }
        public decimal Dep_Amount { get; set; }
        public string Dep_Bank { get; set; }
        public System.DateTime Dep_Collection_StartDate { get; set; }
        public System.DateTime Dep_Collection_EndDate { get; set; }
        public System.DateTime Dep_DepositDate { get; set; }
        public int Dep_Depositor_Emp_Id { get; set; }
        public int Dep_Created_Emp_Id { get; set; }
        public System.DateTime Dep_CreatedDate { get; set; }
        public Nullable<int> Dep_LastUpdate_Emp_Id { get; set; }
        public Nullable<System.DateTime> Dep_LastUpdateDate { get; set; }
        public bool IsSynced { get; set; }
    
        public virtual tblUnits tblUnits { get; set; }
    }
}
