//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUnitSubStation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUnitSubStation()
        {
            this.tblOtherVehicles = new HashSet<tblOtherVehicles>();
            this.tblTrucks = new HashSet<tblTrucks>();
        }
    
        public int Sub_Id { get; set; }
        public int Sub_Unit_Id { get; set; }
        public string Sub_Station_Code { get; set; }
        public string Sub_Station_Name { get; set; }
        public string Sub_Street { get; set; }
        public string Sub_Barangay { get; set; }
        public string Sub_Coordinate { get; set; }
        public string Sub_PhoneNumber { get; set; }
        public string Sub_CellNumber { get; set; }
        public string Sub_Email { get; set; }
        public Nullable<int> Sub_BuildingStatus { get; set; }
        public Nullable<int> Sub_BuildingOwner { get; set; }
        public Nullable<int> Sub_LotOwner { get; set; }
        public Nullable<int> Sub_LotStatus { get; set; }
        public Nullable<decimal> Sub_FloorArea { get; set; }
        public Nullable<decimal> Sub_LotArea { get; set; }
        public Nullable<int> Sub_NumberStorey { get; set; }
        public Nullable<System.DateTime> Sub_ActiviationDate { get; set; }
        public string Sub_Remarks { get; set; }
        public Nullable<int> Sub_FireMarshall_EmpId { get; set; }
        public Nullable<bool> Sub_WithBuilding { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOtherVehicles> tblOtherVehicles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTrucks> tblTrucks { get; set; }
        public virtual tblEmployees tblEmployees { get; set; }
        public virtual tblUnits tblUnits { get; set; }
    }
}
