//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUnitsUserInRole
    {
        public int Unit_UIR_ID { get; set; }
        public int Unit_UIR_Unit_Id { get; set; }
        public int Unit_UIR_Emp_Id { get; set; }
        public bool Unit_UIR_Assessor { get; set; }
        public bool Unit_UIR_Collector { get; set; }
        public bool Unit_UIR_Encoder { get; set; }
        public bool Unit_UIR_Release { get; set; }
        public bool Unit_UIR_Admin { get; set; }
        public bool Unit_UIR_Inspector { get; set; }
        public bool Unit_UIR_PlanEvaluator { get; set; }
    
        public virtual tblEmployees tblEmployees { get; set; }
        public virtual tblUnits tblUnits { get; set; }
    }
}
