//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUnits
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUnits()
        {
            this.tblAfterFireOperations = new HashSet<tblAfterFireOperations>();
            this.tblAssetInventories = new HashSet<tblAssetInventories>();
            this.tblEmployees = new HashSet<tblEmployees>();
            this.tblFireInvestigations = new HashSet<tblFireInvestigations>();
            this.tblInspectionOrders = new HashSet<tblInspectionOrders>();
            this.tblLogisticAssets = new HashSet<tblLogisticAssets>();
            this.tblOtherVehicles = new HashSet<tblOtherVehicles>();
            this.tblPhysicalInventory = new HashSet<tblPhysicalInventory>();
            this.tblSuppliesInventory = new HashSet<tblSuppliesInventory>();
            this.tblTrucks = new HashSet<tblTrucks>();
            this.tblUnitDeposits = new HashSet<tblUnitDeposits>();
            this.tblUnitSubStation = new HashSet<tblUnitSubStation>();
            this.tblUnitsUserInRole = new HashSet<tblUnitsUserInRole>();
            this.tblEstablishments = new HashSet<tblEstablishments>();
            this.tblApplicationPayments = new HashSet<tblApplicationPayments>();
        }
    
        public int Unit_Id { get; set; }
        public string Unit_Code { get; set; }
        public string Unit_StationName { get; set; }
        public string Unit_Address { get; set; }
        public string Unit_PhoneNumber { get; set; }
        public string Unit_Description { get; set; }
        public Nullable<int> Unit_ProvDistrict { get; set; }
        public Nullable<int> Unit_FireMarshall_Emp_Id { get; set; }
        public int Unit_Municipality_Id { get; set; }
        public Nullable<int> Unit_Category { get; set; }
        public string Unit_Street { get; set; }
        public string Unit_Barangays { get; set; }
        public string Unit_Coordinates { get; set; }
        public string Unit_PhoneNumbers { get; set; }
        public string Unit_CellphoneNumbers { get; set; }
        public string Unit_Email { get; set; }
        public Nullable<int> Unit_BuildingStatus { get; set; }
        public Nullable<int> Unit_BuildingOwner { get; set; }
        public Nullable<int> Unit_LotStatus { get; set; }
        public Nullable<int> Unit_LotOwner { get; set; }
        public Nullable<decimal> Unit_FloorArea { get; set; }
        public Nullable<decimal> Unit_LotArea { get; set; }
        public Nullable<int> Unit_NumberStorey { get; set; }
        public Nullable<System.DateTime> Unit_ActivationDate { get; set; }
        public string Unit_Remarks { get; set; }
        public Nullable<int> Unit_ChiefFSES_Emp_Id { get; set; }
        public byte[] Unit_FireMarshall_Signature { get; set; }
        public byte[] Unit_ChiefFSES_Signature { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAfterFireOperations> tblAfterFireOperations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAssetInventories> tblAssetInventories { get; set; }
        public virtual tblCityMunicipality tblCityMunicipality { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployees> tblEmployees { get; set; }
        public virtual tblEmployees tblEmployees1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFireInvestigations> tblFireInvestigations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInspectionOrders> tblInspectionOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLogisticAssets> tblLogisticAssets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOtherVehicles> tblOtherVehicles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPhysicalInventory> tblPhysicalInventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSuppliesInventory> tblSuppliesInventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTrucks> tblTrucks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUnitDeposits> tblUnitDeposits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUnitSubStation> tblUnitSubStation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUnitsUserInRole> tblUnitsUserInRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEstablishments> tblEstablishments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblApplicationPayments> tblApplicationPayments { get; set; }
    }
}
