//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblViolations
    {
        public int Auto_Violation_Id { get; set; }
        public string Violation_Code { get; set; }
        public string Violation_Desc { get; set; }
        public string Violation_Section { get; set; }
        public string Violation_Graceperiod { get; set; }
        public Nullable<int> Violation_OccupancyType { get; set; }
        public string Violation_Compliance { get; set; }
        public Nullable<decimal> Violation_Fine { get; set; }
        public Nullable<int> Violation_Created_EmpId { get; set; }
        public Nullable<System.DateTime> Violation_CreatedDate { get; set; }
        public Nullable<decimal> Violation_Fine2 { get; set; }
        public Nullable<bool> IsSynced { get; set; }
    }
}
