//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWebPages
    {
        public int ViewID { get; set; }
        public string Area { get; set; }
        public string ControllerName { get; set; }
        public string ViewName { get; set; }
        public string ViewFriendlyName { get; set; }
    }
}
