//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFees
    {
        public string Region { get; set; }
        public int RegionId { get; set; }
        public int ProvinceId { get; set; }
        public int UnitId { get; set; }
        public Nullable<decimal> ConstructionTax { get; set; }
        public Nullable<decimal> RealtyTax { get; set; }
        public Nullable<decimal> PremiumTax { get; set; }
        public Nullable<decimal> SalesTax { get; set; }
        public Nullable<decimal> ProceedsTax { get; set; }
        public Nullable<decimal> StorageClearanceFee { get; set; }
        public Nullable<decimal> ConveyanceClearanceFee { get; set; }
        public Nullable<decimal> InstallationClearanceFee { get; set; }
        public Nullable<decimal> FireCodeAdminFine { get; set; }
        public Nullable<decimal> FireSafetyInspectionFee { get; set; }
        public Nullable<decimal> OtherFee { get; set; }
        public Nullable<System.DateTime> ApplicationDate { get; set; }
        public Nullable<int> ApplicationType { get; set; }
        public Nullable<decimal> ForOccupancyFee { get; set; }
        public Nullable<decimal> ForBusinessFee { get; set; }
    }
}
