//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFirePreventionCounter
    {
        public int KeyCounter { get; set; }
        public Nullable<int> IO_TotalCount { get; set; }
        public Nullable<int> IO_Complaint { get; set; }
        public Nullable<int> IO_ForCompliance { get; set; }
        public Nullable<int> IO_ForClosure { get; set; }
        public Nullable<int> IO_Others { get; set; }
        public Nullable<int> IO_AT_IssuanceOfFSIC { get; set; }
        public Nullable<int> IO_AT_IssuedFSIC { get; set; }
        public Nullable<int> IO_AT_IssuanceOfNTC { get; set; }
        public Nullable<int> IO_AT_IssuedNTC { get; set; }
        public Nullable<int> IO_AT_IssuedClosureOrder { get; set; }
        public Nullable<int> IO_AT_ClosurePendingEvaluation { get; set; }
        public Nullable<int> IO_RM_CannotBeLocated { get; set; }
        public Nullable<int> IO_RM_RefuseEntryInspection { get; set; }
        public Nullable<int> EST_TotalCount { get; set; }
        public Nullable<int> EST_High { get; set; }
        public Nullable<int> EST_Moderate_Low { get; set; }
    }
}
