//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFireCodeRevenue
    {
        public int Unit_Id { get; set; }
        public int Municipality_Id { get; set; }
        public int Province_Id { get; set; }
        public int Reg_Id { get; set; }
        public string Est_BusinessName { get; set; }
        public Nullable<decimal> ConstructionTax { get; set; }
        public Nullable<decimal> RealtyTax { get; set; }
        public Nullable<decimal> PremiumTax { get; set; }
        public Nullable<decimal> SalesTax { get; set; }
        public Nullable<decimal> ProceedsTax { get; set; }
        public Nullable<decimal> FireSafetyInspectionFee { get; set; }
        public Nullable<decimal> StorageClearanceFee { get; set; }
        public Nullable<decimal> ConveyanceClearanceFee { get; set; }
        public Nullable<decimal> InstallationClearanceFee { get; set; }
        public Nullable<decimal> FireCodeAdminFine { get; set; }
        public Nullable<decimal> OtherFee { get; set; }
        public string ApplicationTypeName { get; set; }
        public Nullable<System.DateTime> OR_Date { get; set; }
        public string OPS_Number { get; set; }
        public int OR_Number { get; set; }
        public int Application_Type { get; set; }
    }
}
