//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFireInvestigation
    {
        public int FI_Id { get; set; }
        public int FI_Unit_Id { get; set; }
        public string FI_DTPO { get; set; }
        public System.DateTime FI_IncidentReportDate { get; set; }
        public string FI_Informant_Name { get; set; }
        public string FI_Informant_Number { get; set; }
        public string FI_Informant_Address { get; set; }
        public System.DateTime FI_FireStartedDate { get; set; }
        public System.DateTime FI_FirstRespondingUnit_Departure { get; set; }
        public System.DateTime FI_FirstRespondingUnit_Arrival { get; set; }
        public System.DateTime FI_FireOutDate { get; set; }
        public System.DateTime FI_RespondingUnit_StationArrival { get; set; }
        public string FI_AlarmType { get; set; }
        public string FI_FireGround_Commander { get; set; }
        public string FI_Involved_OccupancyType { get; set; }
        public string FI_Involved_OccupancyType_Description { get; set; }
        public Nullable<int> FI_Est_Id { get; set; }
        public string FI_Owner_Occupant { get; set; }
        public string FI_FireCause { get; set; }
        public string FI_FireOrigin { get; set; }
        public string FI_Status_Fire_Incident { get; set; }
        public string FI_Casualty { get; set; }
        public string FI_Injured { get; set; }
        public string FI_EstimatedDamage { get; set; }
        public string FI_TypeIndex { get; set; }
        public string FI_Details { get; set; }
        public string FI_Disposition { get; set; }
        public int FI_Created_Emp_Id { get; set; }
        public System.DateTime FI_CreatedDate { get; set; }
        public Nullable<int> FI_LastUpdate_Emp_Id { get; set; }
        public Nullable<System.DateTime> FI_LastUpdateDate { get; set; }
        public string Est_BusinessName { get; set; }
        public string Est_BusinessAddress { get; set; }
        public string Est_BusinessTradeName { get; set; }
        public string Est_BusinessPermitNumber { get; set; }
        public string Est_OwnerName { get; set; }
        public string Est_AuthorizedRepresentative { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    }
}
