//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFirePreventionIOCounter
    {
        public int KeyCounter { get; set; }
        public int IO_Complaint { get; set; }
        public int IO_ForCompliance { get; set; }
        public int IO_ForClosure { get; set; }
        public int IO_Others { get; set; }
        public int IO_AT_IssuanceOfFSIC { get; set; }
        public int IO_AT_IssuedFSIC { get; set; }
        public int IO_AT_IssuedClosureOrder { get; set; }
        public int IO_AT_ClosurePendingEvaluation { get; set; }
        public int IO_RM_CannotBeLocated { get; set; }
        public int IO_RM_RefuseEntryInspection { get; set; }
        public int IO_Id { get; set; }
        public int Reg_Id { get; set; }
        public int Province_Id { get; set; }
        public int IO_Unit_Id { get; set; }
        public int IO_AT_IssuanceOfNTC { get; set; }
        public int IO_AT_IssuedNTC { get; set; }
    }
}
