//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFirePreventionEstCounter
    {
        public int EST_High { get; set; }
        public int EST_Moderate_Low { get; set; }
        public int Province_Id { get; set; }
        public int Reg_Id { get; set; }
        public int Est_Unit_Id { get; set; }
    }
}
