//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFPSSComplianceTable
    {
        public string ComplianceType { get; set; }
        public System.DateTime IssueDate { get; set; }
        public string Deficiency { get; set; }
        public string Compliance { get; set; }
        public string Remarks { get; set; }
        public int ProvinceId { get; set; }
        public int RegionId { get; set; }
        public int UnitId { get; set; }
    }
}
