//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBFP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwUsersInRole
    {
        public int Emp_Id { get; set; }
        public string Emp_FirstName { get; set; }
        public string Emp_MiddleName { get; set; }
        public string Emp_LastName { get; set; }
        public Nullable<int> Emp_DutyStatus { get; set; }
        public string Role_Name { get; set; }
        public Nullable<int> UIR_ID { get; set; }
        public Nullable<int> UIR_RoleID { get; set; }
        public Nullable<int> Emp_Curr_Unit { get; set; }
        public Nullable<int> Reg_Id { get; set; }
        public Nullable<int> Province_Id { get; set; }
        public string Emp_Number { get; set; }
        public string Rank_Name { get; set; }
        public string Reg_Title { get; set; }
        public string Province_Name { get; set; }
        public string Unit_StationName { get; set; }
    }
}
